### ISSUE TITLE
'Arctic Code Vault Contributor' disappears after deleting repo

### ISSUE THREAD

**Issue by austinwhite** [Schweinepriester/github-profile-achievements#697]
**Issue**
If a user deletes the repos that earned them the 'Arctic Code Vault Contributor' achievement, the achievement disappears. I would assume the same is true for the 'Mars 2020 Contributor' achievement. Even if the repo doesn't exist with the user anymore, they still contributed to these projects.

**Current Behavior**
User deletes the repositories that earned them the 'Arctic Code Vault Contributor' or the 'Mars 2020 Contributor' achievements and the achievements are permanently removed from the users profile.

**Expected Behavior**
User deletes the repositories responsible for earning them the 'Arctic Code Vault Contributor' or the 'Mars 2020 Contributor' achievements and the achievements remain on the users profile.

**Proposed Solution**
For achievements such as the ones mentioned above, they should be tied to users instead of repositories.

**Comment by Schweinepriester** [comment]
Great suggestion!

I suspect this has happend to you? Or do you have otherwise proof of this? Could you go into detail which repo was deleted?

Do note though that I'm not affiliated with GitHub and as such would redirected you to the official channels to report this bug :)

I will leave this issue open for visibility, though!
